# NukeIntel App Configuration - Updated 2025-06-19
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.1"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = "10.2.3"
  ESBUILD_BINARY_PATH = "./node_modules/esbuild/bin/esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
